name: Feature Task Template
description: Standard template for creating new features
title: "Task: [Phase] - [Feature Name]"
labels: ["task"]
assignees: ["jldavid-strat"]
projects: ["jldavid-strat/1"]
body:
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Select the priority of this task
      options:
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: input
    id: estimated_time
    attributes:
      label: Estimated Time
      description: An approximate prediction of how long the will take to complete
      placeholder: "e.g., 6 hours"
    validations:
      required: true

  - type: input
    id: week
    attributes:
      label: Week
      description: Enter the week this task is set to be done
      placeholder: "e.g., Week 3"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - Frontend
        - Backend
        - Database
        - Testing
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear description of what needs to be implemented
      placeholder: "Short description of what the task entails"
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Define what must be true for the task to be considered complete
      placeholder: "
        - [] Specific, measurable criteria
        - [] That define when the task is complete
        - [] Include testing requirements
        "

  - type: textarea
    id: implementation_notes
    attributes:
      label: Implementation Notes
      description: Outline the steps or approach to complete the task
      placeholder: "Describe technical approach, dependencies, or useful resources"

  - type: checkboxes
    id: definition_of_done
    attributes:
      label: Definition of Done
      options:
        - label: Code written and working locally
        - label: Self-reviewed for quality and best practices
        - label: Tests written (if applicable)
        - label: Documentation updated
        - label: Feature deployed and tested
        - label: Ready for optional peer review
