name: Feature Task Template
description: Standard template for creating new features
title: 'Task: [Phase] - [Feature Name]'
labels: ['task']
assignees: ['jldavid-strat']
projects: ['jldavid-strat/1']
body:
  - type: textarea
    id: task-info
    attributes:
      label: 'Task Info'
      description: 'Enter the basic info about the task'
      placeholder: "
        ## Task: [Phase] - [Feature Name]

        **Priority**: High/Medium/Low \n
        **Estimated Time**: X hours \n
        **Week**: Week X \n
        **Category**: Frontend/Backend/Database/Testing"
      value: "
        ## Task: [Phase] - [Feature Name]

        **Priority**: High/Medium/Low \n
        **Estimated Time**: X hours \n
        **Week**: Week X \n
        **Category**: Frontend/Backend/Database/Testing"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear description of what needs to be implemented
      placeholder: 'Short description of what the task entails'
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Define what must be true for the task to be considered complete
      placeholder: "
        - [] Specific, measurable criteria \n
        - [] That define when the task is complete \n
        - [] Include testing requirements \n
        "
      value: "
        - [] Specific, measurable criteria \n
        - [] That define when the task is complete \n
        - [] Include testing requirements \n
        "
  - type: textarea
    id: implementation_notes
    attributes:
      label: Implementation Notes
      description: Outline the steps or approach to complete the task
      placeholder: 'Describe technical approach, dependencies, or useful resources'

  - type: textarea
    id: definition_of_done
    attributes:
      label: Definition of Done
      placeholder: "
        - [] Code written and working locally \n
        - [] Self-reviewed for quality and best practices \n
        - [] Tests written (if applicable) \n
        - [] Documentation updated \n
        - [] Feature deployed and tested \n
        - [] Ready for optional peer review \n
        "
      value: "
        - [] Code written and working locally \n
        - [] Self-reviewed for quality and best practices \n
        - [] Tests written (if applicable) \n
        - [] Documentation updated \n
        - [] Feature deployed and tested \n
        - [] Ready for optional peer review \n
        "
